FROM python:3.13

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libgtk2.0-dev \
    libv4l-dev \
    v4l-utils \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY . .

RUN pip install opencv-python

CMD ["python", "cap_self.py"]
